src/controllers/SiteController.php
<?php

namespace app\controllers;

use app\modules\articles\models\Article;
use app\modules\services\models\Service;
use app\modules\team\models\Human;
use app\modules\videos\models\Video;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionBooks()
    {
        return $this->render('books');
    }

    public function actionArticles()
    {
        $models = Article::find()->all();

        return $this->render('articles', [
            'models' => $models,
        ]);
    }

    public function actionArticle($id)
    {
        $model = Article::findOne($id);

        if ($model == null) {
            throw new NotFoundHttpException();
        }

        return $this->render('article', [
            'model' => $model,
        ]);
    }

    public function actionTest()
    {
        return $this->render('test');
    }

    public function actionServices()
    {
        return $this->render('services');
    }

    public function actionService($id)
    {
        $model = Service::findOne($id);

        if ($model == null) {
            throw new NotFoundHttpException();
        }
        return $this->render('service', [
            'model' => $model,
        ]);
    }

    public function actionTeam()
    {
        $topModels = Human::find()->andWhere(['is_top' => true])->all();
        $models = Human::find()->andWhere(['is_top' => false])->all();

        return $this->render('team', [
            'topModels' => $topModels,
            'models' => $models,
        ]);
    }

    public function actionVideos()
    {
        $models = Video::find()->all();

        return $this->render('videos', [
            'models' => $models,
        ]);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
}

src/views/layouts/_footer.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 */
use app\components\Helper;
use app\widgets\Language;
use yii\helpers\Url;

?>
<footer class="footer">
    <div class="container">
        <div class="footer__inn clearfix">
            <div class="footer__nav clearfix">
                <?php foreach (Helper::getFooterMenu() as $menu): ?>
                    <ul class="reset-list">
                        <?php foreach ($menu as $item): ?>

                            <li><a href="<?= $item['url'] ?>"><?= $item['label'] ?></a></li>
                        <?php endforeach ?>
                    </ul>
                <?php endforeach ?>
            </div>
            <div class="footer__btns">
                <div class="footer__btns__it">
                    <a href="<?= Url::to(['site/test']) ?>" class="btn btn-yellow fw-btn">
                        <?= Yii::t('app', 'Take the OCA test') ?>
                    </a>
                </div>
                <div class="footer__btns__it">
                    <a href="https://www.facebook.com/planeta8d" class="btn btn-blue fw-btn">
                        <svg class="svg-icon fb-icon hidden-sm hidden-xs">
                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fb-icon"></use>
                        </svg>
                        <?= Yii::t('app', 'Follow us on Facebook') ?></a>
                </div>
            </div>
            <div class="footer__info">
                <?= Language::widget() ?>
                <?= Yii::$app->getModule('cms')->blockManager->getWidget('footer-contacts') ?>
                <div class="footer__info__copy">
                    <span>
                        ©<?= date('Y') ?> <?= Yii::t('app', 'Auditor Group "Planet"') ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</footer>

src/views/layouts/_header.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 */
use app\components\Helper;
use yii\bootstrap\Nav;
use yii\helpers\Url;

?>
<header class="header">
    <div class="container">
        <div class="header__top">
            <div class="header__logo"><a href="/"><img src="/img/template/header-logo.png" alt=""></a></div>
            <div class="header__underlogo hidden-xs">
                <div class="header__underlogo__cnt"><span><?= Yii::t('app','A new level') ?></span></div>
            </div>
            <div class="header__top__btn-left hidden-xs">
                <a href="<?= Url::to(['/site/test']) ?>" class="btn btn-yellow fw-btn">
                    <?= Yii::t('app', 'Take the OCA test') ?>
                </a>
            </div>
            <div class="header__top__btn-right hidden-xs">
                <a href="https://www.facebook.com/planeta8d" class="btn btn-blue fw-btn">
                    <svg class="svg-icon fb-icon hidden-sm">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fb-icon"></use>
                    </svg>
                    <?= Yii::t('app','Follow us on Facebook') ?></a>
            </div>
        </div>
    </div>
    <a href="#" class="header__sm-menu-trigger visible-sm"><span></span><span></span><span></span></a>
    <a href="#" class="header__xs-menu-trigger visible-xs"><span></span><span></span><span></span></a>
    <nav class="header__nav">
        <div class="container">
            <?= Nav::widget(['items' => Helper::getMainMenu(), 'options' => ['class' => 'reset-list']]) ?>
        </div>
    </nav>
</header>

src/views/layouts/_modals.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 */
?>

<?php if (isset($this->params['modals']) && is_array($this->params['modals'])): ?>
    <?php foreach ($this->params['modals'] as $modal): ?>
        <?= $modal ?>
    <?php endforeach ?>
<?php endif ?>

src/views/layouts/_svg.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 */
?>
<svg style="position: absolute; width: 0; height: 0;" width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol viewBox="0 0 49.652 49.652" id="fb-icon">
            <path fill="currentColor" d="M24.826,0C11.137,0,0,11.137,0,24.826c0,13.688,11.137,24.826,24.826,24.826c13.688,0,24.826-11.138,24.826-24.826    C49.652,11.137,38.516,0,24.826,0z M31,25.7h-4.039c0,6.453,0,14.396,0,14.396h-5.985c0,0,0-7.866,0-14.396h-2.845v-5.088h2.845    v-3.291c0-2.357,1.12-6.04,6.04-6.04l4.435,0.017v4.939c0,0-2.695,0-3.219,0c-0.524,0-1.269,0.262-1.269,1.386v2.99h4.56L31,25.7z"></path>
        </symbol>
        <symbol viewBox="0 0 382.117 382.117" id="mail-icon">
            <path fill="currentColor" d="M336.764,45.945H45.354C20.346,45.945,0,65.484,0,89.5v203.117c0,24.016,20.346,43.555,45.354,43.555h291.41  c25.008,0,45.353-19.539,45.353-43.555V89.5C382.117,65.484,361.772,45.945,336.764,45.945z M336.764,297.72H45.354  c-3.676,0-6.9-2.384-6.9-5.103V116.359l131.797,111.27c2.702,2.282,6.138,3.538,9.676,3.538l22.259,0.001  c3.536,0,6.974-1.257,9.677-3.539l131.803-111.274v176.264C343.664,295.336,340.439,297.72,336.764,297.72z M191.059,192.987  L62.87,84.397h256.378L191.059,192.987z"></path>
        </symbol>
        <symbol viewBox="0 0 365.449 365.449" id="phone-icon">
            <path fill="currentColor" d="M281.507,10.85C274.279,3.614,265.71,0,255.813,0H109.637c-9.9,0-18.464,3.617-25.697,10.85   c-7.233,7.229-10.85,15.796-10.85,25.693v292.361c0,9.896,3.617,18.462,10.85,25.693c7.233,7.234,15.797,10.852,25.697,10.852   h146.176c9.896,0,18.466-3.621,25.693-10.852c7.234-7.231,10.852-15.797,10.852-25.693V36.543   C292.358,26.646,288.745,18.083,281.507,10.85z M159.885,36.543h45.685c3.046,0,4.565,1.523,4.565,4.569   c0,3.045-1.52,4.57-4.565,4.57h-45.685c-3.045,0-4.568-1.525-4.568-4.57C155.316,38.066,156.839,36.543,159.885,36.543z    M198.861,345.036c-4.476,4.469-9.852,6.707-16.135,6.707c-6.28,0-11.656-2.238-16.13-6.707c-4.474-4.477-6.711-9.856-6.711-16.132   c0-6.283,2.24-11.66,6.711-16.133c4.471-4.469,9.851-6.714,16.13-6.714c6.284,0,11.66,2.245,16.135,6.714   c4.473,4.473,6.708,9.85,6.708,16.133S203.331,340.56,198.861,345.036z M264.954,283.225c0,2.471-0.903,4.62-2.714,6.424   c-1.813,1.807-3.949,2.707-6.42,2.707H109.637c-2.474,0-4.615-0.903-6.423-2.707s-2.712-3.953-2.712-6.424V82.229   c0-2.474,0.903-4.617,2.712-6.423c1.809-1.805,3.949-2.714,6.423-2.714h146.176c2.478,0,4.616,0.905,6.427,2.714   c1.811,1.807,2.71,3.949,2.71,6.423v200.995H264.954z"></path>
        </symbol>
        <symbol viewBox="0 0 30.598 30.598" id="play-icon">
            <path fill="currentColor" d="M2.806,30.598c-0.151,0-0.303-0.039-0.438-0.118c-0.271-0.155-0.437-0.444-0.437-0.757V0.875  c0-0.312,0.167-0.602,0.437-0.757c0.27-0.157,0.605-0.157,0.874,0l24.986,14.425c0.271,0.155,0.439,0.443,0.439,0.757  c0,0.312-0.167,0.601-0.439,0.757L3.243,30.48C3.108,30.559,2.958,30.598,2.806,30.598z M3.681,2.389v25.819L26.043,15.3  L3.681,2.389z"></path>
        </symbol>
        <symbol viewBox="0 0 229.153 229.153" id="check-icon">
            <path fill="currentColor" d="M92.356,223.549c7.41,7.5,23.914,5.014,25.691-6.779c11.056-73.217,66.378-134.985,108.243-193.189   C237.898,7.452,211.207-7.87,199.75,8.067C161.493,61.249,113.274,117.21,94.41,181.744   c-21.557-22.031-43.201-43.853-67.379-63.212c-15.312-12.265-37.215,9.343-21.738,21.737   C36.794,165.501,64.017,194.924,92.356,223.549z"></path>
        </symbol>
    </defs>
</svg>

src/views/layouts/article.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 * @var $content string
 */
?>

<?php $this->beginContent('@app/views/layouts/main.php') ?>
<?= $content ?>
<?php $this->endContent() ?>

src/views/layouts/main.old.php
<?php
use app\assets\AppAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse',
        ],
    ]);
    echo Nav::widget([
        'encodeLabels' => false,
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => Yii::t('app', 'Home'), 'url' => ['/site/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?php foreach (Yii::$app->session->getAllFlashes() as $type => $text): ?>

            <div class="alert alert-<?= $type ?>">
                <?= $text ?>
            </div>

        <?php endforeach; ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; NRE <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

src/views/layouts/main.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Yii::$app->getModule('cms')->blockManager->getWidget('head') ?>
    <?= Html::csrfMetaTags() ?>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic"
          rel="stylesheet">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>

<?= $this->render('_svg') ?>

<div class="page-wrapp">
    <div class="content-without-footer">
        <?= $this->render('_header') ?>
        <?= $content ?>
    </div>
    <?= $this->render('_footer') ?>
</div>

<?= $this->render('_modals') ?>

<script data-main="/js/main" src="/js/require.js"></script>
<?php $this->endBody() ?>
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '327597067689280',
            xfbml      : true,
            version    : 'v2.10'
        });
        FB.AppEvents.logPageView();
    };
</script>
<?= Yii::$app->getModule('cms')->blockManager->getWidget('footer') ?>
</body>
</html>
<?php $this->endPage() ?>

src/views/site/article.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 * @var $model \app\modules\articles\models\Article
 */

$this->title = $model->name;
?>

<div class="article">
    <div class="article__top">
        <div class="article__top__img ofit-block"><img src="<?= $model->image ?>" alt=""></div>
        <div class="container">
            <div class="article__top__title">
                <h1><?= $model->name ?></h1>
            </div>
            <div class="article__top__txt">
                <p><?= $model->description ?></p>
            </div>
        </div>
    </div>
</div>
<div class="article__cnt">
    <div class="container">
        <div class="article__block-list">
            <?php foreach ($model->blocks as $block): ?>
                <div class="article__block">
                    <?= $block->getWidget() ?>
                </div>
            <?php endforeach ?>
        </div>
        <div class="article__author">
            <span><?= $model->author ?></span>
        </div>
    </div>

</div>

src/views/site/articles.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 * @var $models \app\modules\articles\models\Article[]
 */
use yii\helpers\Url;

$this->title = Yii::t('app', 'Articles');

$chunks = array_chunk($models, 2);
?>

<div class="articles">
    <div class="container">
        <div class="team__title">
            <h1><span><?= $this->title ?></span></h1>
        </div>
        <div class="articles__list">
            <?php foreach ($chunks as $models): ?>
                <div class="row">
                    <?php foreach ($models as $model):
                        $url = Url::to(['/site/article', 'id' => $model->id]);
                        ?>
                        <div class="col-md-6">
                            <div class="articles__item">
                                <div class="articles__item__img ofit-block">
                                    <img src="<?= $model->image ?>" alt="<?= $model->name ?>">
                                </div>
                                <div class="articles__item__inn">
                                    <div class="articles__item__title">
                                        <span><?= $model->name ?></span>
                                    </div>
                                    <div class="articles__item__btn">
                                        <a href="<?= $url ?>"
                                           class="btn btn-yellow fw-btn hidden-xs"><?= Yii::t('app', 'Learn more') ?> ›</a>
                                        <a href="<?= $url ?>" class="mrelife__cnt__mob-link hidden-lg hidden-md hidden-sm">
                                            <i><?= Yii::t('app', 'Learn more') ?></i> ›
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>

src/views/site/books.php
<?php

/* @var $this yii\web\View */
use app\modules\books\widgets\BookList;

$this->title = Yii::t('app', 'Our books');
?>

<div class="books">
    <div class="container">
        <div class="team__title">
            <h1><span><?= $this->title ?></span></h1>
        </div>
        <div class="books__subtitle">
            <span><?= Yii::t('app', 'Many people think that their success and prosperity depends solely on luck. But this is not so. Life, business, work are subject to certain laws, knowing that a person can achieve his goals much faster and more efficiently. These laws, as well as tools for better survival are described in the following books, which you can order in the "Planet" group.') ?></span>
        </div>

        <?= BookList::widget() ?>
    </div>
</div>

src/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>


</div>

src/views/site/index.php
<?php

/* @var $this yii\web\View */
use app\widgets\Fb;

$this->title = Yii::$app->name;
?>
<?= Yii::$app->getModule('cms')->blockManager->getWidget('main-slider-' . Yii::$app->language) ?>
<?= Yii::$app->getModule('cms')->blockManager->getWidget('leaders-' . Yii::$app->language) ?>
<?= Yii::$app->getModule('cms')->blockManager->getWidget('main-service-' . Yii::$app->language) ?>
<?= Fb::widget() ?>

src/views/site/service.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 * @var $model \app\modules\services\models\Service
 */
use app\modules\services\components\BlockManager;



$this->title = $model->name;
?>

<?php foreach ($model->blocks as $block): ?>
    <?= $block->getWidget() ?>
<?php endforeach ?>
 

src/views/site/services.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 */
use app\modules\services\widgets\Services;
use app\widgets\Office;
use app\widgets\Title;
$this->title = Yii::t('app', 'Services');
?>

<div class="services">
    <div class="container">
        <?= Title::widget(['title' => $this->title]) ?>

        <?= Services::widget() ?>

        <?= Office::widget() ?>
    </div>
</div>

src/views/site/team.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 *
 * @var $this \yii\web\View
 * @var $topModels \app\modules\team\models\Human[]
 * @var $models \app\modules\team\models\Human[]
 */

$this->title = Yii::t('app', 'Our Team');
?>

<div class="team container">
    <div class="team__title">
        <h1><span><?= $this->title ?></span></h1>
    </div>
    <div class="team__subtitle">
        <span>Группа "Планета" была создана 8 лет назад. Мы помогли многим людям со всех уголков планеты.</span>
    </div>
    <div class="team__tops">
        <?php foreach ($topModels as $model): ?>
            <div class="team__item">
                <div class="team__item__img"><img src="<?= $model->image ?>" alt="<?= $model->name ?>"></div>
                <div class="team__item__name"><span><?= $model->name ?></span></div>
                <div class="team__item__prof"><span><?= $model->description ?></span></div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="team__peoples">
        <?php foreach ($models as $model): ?>
            <div class="team__item">
                <div class="team__item__img"><img src="<?= $model->image ?>" alt="<?= $model->name ?>"></div>
                <div class="team__item__name"><span><?= $model->name ?></span></div>
                <div class="team__item__prof"><span><?= $model->description ?></span></div>
            </div>
        <?php endforeach ?>
    </div>
</div>

src/views/site/videos.php
<?php
/**
 * @author    Dmytro Karpovych
 * @copyright 2017 NRE
 * @var $models \app\modules\videos\models\Video[]
 * @var $this \yii\web\View
 */
$this->title = Yii::t('app', 'Video');

$this->params['modals'][] = <<<HTML
        <div id="videoModal" class="modal fade modal-scale video-modal">
          <div class="modal-dialog">
            <div class="modal-content"><a href="#" data-dismiss="modal" class="modal-close"></a>
              <div class="video-modal__video-wrap"></div>
            </div>
          </div>
        </div>
HTML;

$chunks = array_chunk($models, 2);
?>

<div class="videos">
    <div class="container">
        <div class="team__title">
            <h1><span><?= $this->title ?></span></h1>
        </div>
        <div class="videos__list">
            <?php foreach ($chunks as $models): ?>
                <div class="row">
                    <?php foreach ($models as $model): ?>
                        <div class="col-md-6">
                            <div class="videos__item">
                                <div class="videos__item__img ofit-block">
                                    <img src="<?= $model->image ?>" alt="<?= $model->name ?>">
                                    <a href="#" data-video="<?= $model->url ?>" class="videos__item__play">
                                        <svg class="svg-icon play-icon">
                                            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#play-icon"></use>
                                        </svg>
                                    </a>
                                </div>
                                <div class="videos__item__title"><span><?= $model->name ?></span></div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>